theme = "base16_terminal"
[editor]
line-number = "relative"
true-color = true
auto-pairs = true
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
[editor.soft-wrap]
enable = true
